version: '3.7'

networks:
  emasa-network:
    driver: bridge
volumes:
  emasa-pg:
    external: true
  emasa-redis:
    external: true
  emasa-mongo:
    external: true 
services:
  emasa-postgres:
    image: postgres
    container_name: emasa-postgres
    restart: always
    tty: true
    volumes:
    - emasa-pg:/postgres/pg
    environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASS}
    - POSTGRES_DB=${DB_NAME}
    ports:
    - "5432:5432"
  emasa-redis:
    image: bitnami/redis:latest
    container_name: emasa-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - emasa-redis:/bitnami/redis/data
    networks:
      - emasa-network
#version: "3.7"

#  networks:
#    emasa-network:
#      driver: bridge

#  services:
#    emasa-api:
#      build: .
#      volumes:
#        - .:/home/node/api
#      depends_on:
#        - emasa-postgres
#        - emasa-redis
#      networks:
#        - emasa-network
#      links:
#        - emasa-postgres
#        - emasa-redis
#      container_name: emasa-api
#      command: yarn dev
#      ports:
#        - 4000:4000
#    emasa-queue:
#      build: .
#      volumes:
#        - .:/home/node/api
#      depends_on:
#        - emasa-postgres
#        - emasa-redis
#      networks:
#        - emasa-network
#      links:
#        - emasa-postgres
#        - emasa-redis
#      container_name: emasa-queue
#      command: yarn queue
#    emasa-redis:
#      image: bitnami/redis:latest
#      container_name: emasa-redis
#      restart: always
#      environment:
#        - ALLOW_EMPTY_PASSWORD=no
#        - REDIS_PASSWORD=${REDIS_PASS}
#      ports:
#        - "6379:6379"
#      volumes:
#        - /tmp/redis:/bitnami/redis/data
#      networks:
#        - emasa-network
#    emasa-postgres:
#      image: postgres
#      container_name: ms-employee-db
#      restart: always
#      tty: true
#      volumes:
#        - pg-employee:/var/lib/postgresql/data
#      environment:
#        - POSTGRES_USER=emasa
#        - POSTGRES_PASSWORD=emasa03210
#        - POSTGRES_DB=emasa_ti
#      ports:
#        - "5432:5432"
